const dukanProducts = [
  {
    "n": "GOLDEN TURMERIC POWDER",
    "b": "GTP-1026",
    "c": "",
    "i": "TURMERIC",
    "rates": "100 gm-80,         250 gms-200,       500 gms-400,   1 kg-800",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "SELAM TURMERIC POWDER",
    "b": "STP-1026",
    "c": "",
    "i": "TURMERIC",
    "rates": "100 gm-72,         250 gms-180,       500 gms-360,   1 kg- 720",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "CHILLI POWDER KASHMIRI",
    "b": "CPKKMU1-1026",
    "c": "",
    "i": "Chilli,\nRice bran edible oil not more than 2%.\n[Saturated fat - 3%, Trans fat - 0.1%]",
    "rates": "100 gm-160,         250 gms-400,       500 gms-800,   1 kg-1600",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "MALVANI MIX SPECIAL MASALA",
    "b": "MMSM-1026",
    "c": "",
    "i": "(In Descending Order By Weight) Red Chillies, Coriander, Poppy Seeds, Garlic, Onion, Coconut, Nutmeg, Turmeric, Cumin, Shahjeera, Cardamom, Cloves, Mace, Black Pepper, Fenugreek Seeds, Star Anise, Stoneflower, Fennel Seeds, Black Cardamom, Bay Leaves, Asafoetida, Sichuan Pepper, Iodised Salt.",
    "rates": "100 gm-90,         250 gms-225,       500 gms-450,   1 kg- 900",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "CORIANDER GREEN SEASONING",
    "b": "CGSKMU1-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) CORIANDER, TURMERIC, EDIBLE RICE BRAN OIL",
    "rates": "100 gm-72,         250 gms-180,       500 gms-360,   1 kg- 720",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "DHANAJEERA (MIX MASALA POWDER)",
    "b": "DJMMPKMU1-1026",
    "c": "",
    "i": "(In Descending Order By Weight) CORIANDER, CUMIN, TURMERIC,",
    "rates": "100 gm-88,         250 gms-220,       500 gms-440,   1 kg- 880",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "CORIANDER SARAS SEASONING",
    "b": "CSS-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) CORIANDER, TURMERIC, EDIBLE RICE BRAN OIL",
    "rates": "100 gm-60         250 gms-150       500 gms-300   1 kg-600",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "RESHAMPATTI KHANDELA CHILLI BLEND SEASONING",
    "b": "RKCBS-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) Chilli, Salt, Edible Rice Bran Oil.",
    "rates": "100 gm-90,         250 gms-225,       500 gms-450,   1 kg- 900",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "DANDICUT KHANDELA CHILLI BLEND SEASONING",
    "b": "DKCBS-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) Chilli, Salt, Edible Rice Bran Oil.",
    "rates": "100 gm-90,         250 gms-225,       500 gms-450,   1 kg- 900",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "PALITANA KHANDELA CHILLI BLEND SEASONING",
    "b": "PKCBS-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) Chilli, Salt, Edible Rice Bran Oil.",
    "rates": "100 gm-72,         250 gms-180,       500 gms-360,   1 kg- 720",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "KASHMIRI KHANDELA CHILLI BLEND SEASONING",
    "b": "KKCBS-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) Chilli, Salt, Edible Rice Bran Oil.",
    "rates": "100 gm-160,         250 gms-400,       500 gms-800,   1 kg-1600",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "CHILLI POWDER SP  LAL",
    "b": "CPSPLV-1026",
    "c": "",
    "i": "Chilli,\nRice bran edible oil not more than 2%.\n[Saturated fat - 3%, Trans fat - 0.1%]",
    "rates": "100 gm-100         250 gms-250       500 gms-500   1 kg- 1000",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "CHILLI POWDER SP LAL UNCHA",
    "b": "CPSPLCCV-1026",
    "c": "",
    "i": "Chilli,\nRice bran edible oil not more than 2%.\n[Saturated fat - 3%, Trans fat - 0.1%]",
    "rates": "100 gm-100         250 gms-250       500 gms-500   1 kg- 1000",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "GINGER SEASONING",
    "b": "GSM-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) GINGER, RICE, EDIBLE RICE BRAN OIL",
    "rates": "100 gm-100         250 gms-250       500 gms-500   1 kg- 1000",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "CUMIN SEASONING",
    "b": "CSM-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) CUMIN, EDIBLE RICE BRAN OIL",
    "rates": "100 gm-80,         250 gms-200,       500 gms-400,   1 kg-800",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "DRY MANGO SEASONING",
    "b": "DMSM-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) DRY MANGO, RICE FLOUR, EDIBLE RICE BRAN OIL",
    "rates": "100 gm-60         250 gms-150       500 gms-300   1 kg-600",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "BLACK PEPPER SEASONING",
    "b": "BPS-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) BLACK PEPPER, EDIBLE RICE BRAN OIL",
    "rates": "100 gm-140    , 250 gms-350  , 500 gms-  700   , 1 kg- 1400",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "METHI SEASONING",
    "b": "MS-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) FENUGREEK SEED, TURMERIC, EDIBLE RICE BRAN OIL",
    "rates": "100 gm-40         250 gms-100       500 gms-200   1 kg- 400",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "CORIANDER SEASONING",
    "b": "CS-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) CORIANDER, TURMERIC, EDIBLE RICE BRAN OIL",
    "rates": "100 gm-40         250 gms-100       500 gms-200   1 kg- 400",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "SAMBHAR CHILLI BLEND SEASONING",
    "b": "SCBS-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) Chilli, Salt, Split Mustard seeds, Split fenugreek seeds, mustard oil, asafoetida.",
    "rates": "100 gm-80,         250 gms-200,       500 gms-400,   1 kg-800",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "SAMBHAR KASHMIRI CHILLI BLEND SEASONING",
    "b": "SKCBS-1026",
    "c": "category - seasoning",
    "i": "(In Descending Order By Weight) Chilli, Salt, Split Mustard seeds, Split fenugreek seeds, mustard oil, asafoetida.",
    "rates": "100 gm-140    , 250 gms-350  , 500 gms-  700   , 1 kg- 1400",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "JEERA SUPER",
    "b": "JS1026",
    "c": "",
    "i": "(cumin seeds",
    "rates": "100 gm-90,         250 gms-225,       500 gms-450,   1 kg- 900",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "RAI",
    "b": "R1026",
    "c": "",
    "i": "mustard seeds",
    "rates": "100 gm-40         250 gms-100       500 gms-200   1 kg- 400",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  },
  {
    "n": "STICKER SIZE- 50 X 90 MM",
    "b": "STICKER SIZE- 80 X 25 MM",
    "c": "",
    "i": "",
    "rates": "",
    "e": 0,
    "p": 0,
    "cb": 0,
    "tf": 0,
    "sf": 0,
    "so": 0
  }
];
